### ISSUE TITLE
Materials go into the Items tab of the Inventory

### ISSUE THREAD

**Issue by Cuddlecreeper8** [GarnetSunset/Ishin-Machine-Translation#9] opened 2021-04-13 16:49 UTC
Materials go into the Items tab of the Inventory
![Screenshot 2021-04-13 124836](https://user-images.githubusercontent.com/34997487/114590318-996b5200-9c56-11eb-9864-c25cd0f7886a.png)

**Comment by GarnetSunset** [comment] 2021-04-13 16:52
Good catch, not sure what that issue is

**Comment by Timo654** [comment] 2021-04-13 17:51
Pretty much just a duplicate of #4.

**Closed by Timo654** 2021-04-13 17:51 UTC
